### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LordOfTheSnow** [dmparker0/nflsim#2]
Running 

`simulation = nfl.Simulate(season=2020, n_sims=10000)`

(or any other season)

results in an "IndexError: list index out of range"

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/nflsim/core.py", line 29, in __init__
    system.calculate(gamelog=played_adj, season=self.season)
  File "/home/user/.local/lib/python3.8/site-packages/nflsim/pwr.py", line 85, in calculate
    tbl = html.select('table[class*=stats]')[0]
IndexError: list index out of range
```
I am using Python 3.8.5 under Linux Minit.

**Comment by Grandpa-G** [comment]
I did a little investigation and one thing I find is that the html returned from football outsiders' website only contains several rows of valid data since there is no way to directly login into their website.

I think you would have to scrap the login process to get in to get all the data, though I may be wrong.

**Comment by MrStrats** [comment]
So, you are probably right about that for the DVOA data as it does have a log in, but that can be corrected with some code. Unfortunately, even if you disable DVOA and only allow the other 2 data sites (Sagarin and FPI ) the same issue occurs. 
The problem is in how the webscrapping is trying to get the data. The websites must have been updated and the data no longer pulls correctly. If you disable everything except the SRS it does work correctly. 
To do this you would need to write the following:

regression = nfl.Regression(n_games=10)
systems = nfl.PWRsystems(srs=nfl.SRS(regress_to=regression))

Furthermore, I have succeeded in getting the other data sites to pull correctly, unfortunately, there are more issues inside the code that wont allow me to get the data to flow through correctly.. I'm working on rebuilding this and possibly making it even more robust.

Currently, with FPI enabled and SRS enabled it is getting hung up on this:
KeyError: ('NFC', 'Championship', 1)

I'm working through it now.
